// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';

const env = process.env.NODE_ENV === 'production' ? '.env.production' : '.env.development';

config({ path: env });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'] || '', // usamos DIRECT_URL en migraciones
  },
});
